apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::617480992998:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1NTS29UBQRWDY
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::617480992998:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-27T09:58:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1212"
  uid: a57206c8-c938-486f-9591-7aeb9d98cf4d