apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::617480992998:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1HCY30H629TSL
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-28T07:06:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1075"
  uid: 9b318c31-e9bf-4e2a-b1ac-4a430cf5211c
